version: "3.7"

services:
  app:
    container_name: server_telework
    restart: always
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: [ "/home/app/docker/backend/server-entrypoint.sh" ]
    volumes:
      - static_volume:/home/app/backend/static
      - media_volume:/home/app/backend/media
    expose:
      - 8000
    env_file:
      - ./app/core/.env
  nginx:
    container_name: nginx_telework
    build: ./docker/nginx
    restart: always
    volumes:
      - static_volume:/home/app/backend/static
      - media_volume:/home/app/backend/media
    ports:
      - 4002:80 #externe port of the serveur
    depends_on:
      - app
    logging:
      options:
        max-size: 10m

networks:
  network1:
    external: true
    name: telework_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  static_volume: {}
  media_volume: {}
