# Generated by Django 4.2.10 on 2024-03-08 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeTeleTravail',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('Necessite_professionnelle', 'Nécessité professionnelle'), ('Conditions_env_defavorables', 'Conditions environnementales défavorables'), ('Perturbations_sociales_transp', 'Perturbations sociales et de transport'), ('Cas_de_force_majeure', 'Cas de force majeure'), ('Demandes_personnelles_exceptionnelles', 'Demandes personnelles exceptionnelles')], max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('lieu', models.CharField(max_length=100)),
                ('commentaire', models.TextField()),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('refuse', 'Refusé'), ('accepte', 'Accepté')], default='en_attente', editable=False, max_length=10)),
                ('date_signature_superieur', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, simple_history.models.HistoricalRecords),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, simple_history.models.HistoricalRecords),
        ),
        migrations.CreateModel(
            name='TypePersonnel',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('agent', 'Agent'), ('superieur_hierarchique', 'Supérieur hiérarchique')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, simple_history.models.HistoricalRecords),
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service')),
                ('type_personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typepersonnel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, simple_history.models.HistoricalRecords),
        ),
        migrations.CreateModel(
            name='MotifRefus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motif_refus', to='app.demandeteletravail')),
            ],
        ),
        migrations.CreateModel(
            name='LiaisonAgentSuperieur',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='app.personnel')),
                ('superieur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superieur', to='app.personnel')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, simple_history.models.HistoricalRecords),
        ),
        migrations.AddField(
            model_name='demandeteletravail',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personnel'),
        ),
    ]
