# Generated by Django 4.2.3 on 2024-07-11 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeTeleTravail",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motif",
                    models.CharField(
                        choices=[
                            ("Necessite_professionnelle", "Nécessité professionnelle"),
                            (
                                "Conditions_env_defavorables",
                                "Conditions environnementales défavorables",
                            ),
                            (
                                "Perturbations_sociales_transp",
                                "Perturbations sociales et de transport",
                            ),
                            ("Cas_de_force_majeure", "Cas de force majeure"),
                            (
                                "Demandes_personnelles_exceptionnelles",
                                "Demandes personnelles exceptionnelles",
                            ),
                            ("Autres", "Autres"),
                        ],
                        max_length=50,
                    ),
                ),
                ("autre_motif", models.CharField(blank=True, max_length=50)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "lieu",
                    models.CharField(
                        choices=[("Domicile", "Domicile"), ("Autre", "Autre")],
                        default="Domicile",
                        max_length=100,
                    ),
                ),
                (
                    "autre_champ_si_nécessaire",
                    models.CharField(blank=True, max_length=50),
                ),
                ("commentaire", models.TextField(blank=True)),
                (
                    "date_demande",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en attente", "En attente"),
                            ("Refusé", "Refusé"),
                            ("Accepté", "Accepté"),
                        ],
                        default="en attente",
                        editable=False,
                        max_length=10,
                    ),
                ),
                (
                    "date_signature_superieur",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, simple_history.models.HistoricalRecords),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, simple_history.models.HistoricalRecords),
        ),
        migrations.CreateModel(
            name="TypePersonnel",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        choices=[
                            ("agent", "Agent"),
                            ("superieur_hierarchique", "Supérieur hiérarchique"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, simple_history.models.HistoricalRecords),
        ),
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_photos/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telework.service",
                    ),
                ),
                (
                    "type_personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telework.typepersonnel",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, simple_history.models.HistoricalRecords),
        ),
        migrations.CreateModel(
            name="MotifRefus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motif", models.TextField()),
                (
                    "demande",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="motif_refus",
                        to="telework.demandeteletravail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiaisonAgentSuperieur",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent",
                        to="telework.personnel",
                    ),
                ),
                (
                    "superieur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="superieur",
                        to="telework.personnel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, simple_history.models.HistoricalRecords),
        ),
        migrations.AddField(
            model_name="demandeteletravail",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="telework.personnel"
            ),
        ),
    ]
