# Generated by Django 4.2.10 on 2024-03-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='personnel_photos/', verbose_name='Photo'),
        ),
    ]
