# Generated by Django 4.2.3 on 2024-07-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telework", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandeteletravail",
            name="motif",
            field=models.CharField(
                choices=[
                    ("Nécessité professionnelle", "Nécessité professionnelle"),
                    (
                        "Conditions environnementales défavorables",
                        "Conditions environnementales défavorables",
                    ),
                    (
                        "Perturbations sociales et de transport",
                        "Perturbations sociales et de transport",
                    ),
                    ("Cas de force majeure", "Cas de force majeure"),
                    (
                        "Demandes personnelles exceptionnelles",
                        "Demandes personnelles exceptionnelles",
                    ),
                    ("Autres", "Autres"),
                ],
                max_length=50,
            ),
        ),
    ]
