# Generated by Django 4.2.3 on 2024-07-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telework", "0002_alter_personnel_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="password",
            field=models.CharField(max_length=200),
        ),
    ]
