# Generated by Django 5.0.3 on 2024-03-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_personnel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeteletravail',
            name='lieu',
            field=models.CharField(choices=[('Domicile', 'Domicile'), ('Autre', 'Autre')], default='Domicile', max_length=100),
        ),
        migrations.AlterField(
            model_name='demandeteletravail',
            name='motif',
            field=models.CharField(choices=[('Necessite_professionnelle', 'Nécessité professionnelle'), ('Conditions_env_defavorables', 'Conditions environnementales défavorables'), ('Perturbations_sociales_transp', 'Perturbations sociales et de transport'), ('Cas_de_force_majeure', 'Cas de force majeure'), ('Demandes_personnelles_exceptionnelles', 'Demandes personnelles exceptionnelles'), ('Autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Photo'),
        ),
    ]
