# Generated by Django 4.2.3 on 2025-03-03 13:36

from django.db import migrations, models
import django.db.models.deletion
import telework.models


class Migration(migrations.Migration):

    dependencies = [
        ('telework', '0003_alter_personnel_type_personnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='service',
            field=models.ForeignKey(blank=True, default=telework.models.Service.get_default_pk, null=True, on_delete=django.db.models.deletion.CASCADE, to='telework.service'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='type_personnel',
            field=models.ForeignKey(blank=True, default=telework.models.TypePersonnel.get_default_pk, null=True, on_delete=django.db.models.deletion.CASCADE, to='telework.typepersonnel'),
        ),
    ]
