# Generated by Django 4.2.3 on 2024-07-23 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("telework", "0003_alter_personnel_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="service",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="telework.service",
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="type_personnel",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="telework.typepersonnel",
            ),
        ),
    ]
