# Generated by Django 4.2.3 on 2024-07-23 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("telework", "0004_alter_personnel_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="telework.service",
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="type_personnel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="telework.typepersonnel",
            ),
        ),
    ]
