# Generated by Django 5.0.3 on 2024-05-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_demandeteletravail_motif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeteletravail',
            name='autre_champ_si_nécessaire',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='demandeteletravail',
            name='autre_motif',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
